### ISSUE TITLE
Link to full code samples does not work

### ISSUE THREAD

**Issue by nikos** [confluentinc/ksql-recipes-try-it-at-home#16]
The link at the very end of the README turns out to link to a non existing page:
"Full code sample with data generator, database lookups and Elasticsearch/Kibana visualisation"
https://github.com/confluentinc/demo-scene/blob/master/ksql-atm-fraud-detection/ksql-atm-fraud-detection.adoc

**Comment by vsyu** [comment]
@rmoff should it be this link? https://github.com/confluentinc/demo-scene/tree/master/ksql-atm-fraud-detection.
